language: go
go:
- 1.14.4
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
- sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - main
env:
  global:
  - secure: NZ05IoH96x5MFzRvYz0jIx3+hz0YNRVWr1kIo6MsFQzlYafTUENdI77OrEyMYckjATl9G+mwNTemjdup36ChBJwyXN4tevXBPJbHhQhp8ztt1n3UIFRKgEIopgtgAxVOgBhbp6yK0CmP7dxWUQX5DsKQ/GDh1LiCeyjDToy5eFaUi4aznbDrW5bEWIKS+6m/cqAOOGT8Kv+siLCwHknLs7Xt9GuEE/oKpi+HKp4vHdGBN8h9Dwvz9OWG4oj+3LGLna8XulZVHi3k5c8vMNxPlfb4zoqGoIutoH2KOvmL02GhDr7R3SFQHQQk7Osava3XBOysqN2i2cGxv2NDyb7oU2BlIdPaoqcU7U30tkydusoDiAmRye10sADXWObsTVg20nJ3Cv8x9AcsQ3DzUlll6ETtdIRf6kia+auCGf4If/I42lTX4+hkLD/im7T24XHo5jcxYxTELTysNO+kRp6rQyK1+SVU5+lA17u+pR+zZ3/jWLcgTMAWByLsZgA9DAhMqMsWL/uJnrt6xP0pKejaGaTC7qjoCLgR6BFzOEEuJ914ILO6mGO0RQN6sQUWtRwM5UhMu1Kvt1L+ruwhT/4JNbRTCmtavM7a4n9jJqS+3VmASWcUZQX1CNd6FbCgjeMqw+gHygJxKw1/S34qx+D0gRmtS9QsUlFmJg64HgtZD/8=
  - secure: qDBuJrg8CBIniQkl32j5Pq40i5c+KmFCW2PrJzbvCoRdE33lN98LjRXqmImyPmVkjFrBYc+7wOvCRob+h42zuuGtaR2SB1JLhRIY+MV2MBwaCZsc0BlEybzMxdHLaR1LnPo/3tG6KBqtrH66lH/GBiTRClbFSznF3i32NA/ER6hQZ4vSGW+A7qwKHnt1/8i3/1yAI+ElQpNB1Iv9ALXoBWXMGkF6aKU4XfGnkUeAynAEJJKUsBBPs9pNsKANMVblREB2NUiwZmdl505dNXeuDqwIuxaQrvJIXIzqLxAOb4gqLYrqAfPiyjO2iwexWfSqlnRNlKPGqNWqxxqZaInmrIHuR4yHY6dnvs5gq9vVyQg2VFOOiR4I6qXulfSJdRaIZpPy5BPbT2LTVnB0v7g02sli5vitQiDCRsQjhuk8Hs86gKcPO25VUl9P0Jk1qOoS+lBzUKBBCkxSeplYZip7CZGPc3hRfvv0wQf1c2g6uwvzuenYjs+Wr4cjA+54oGz8F1chuEoO/ErYxv3FHRit86+FRR/AbLi7Oy2F+THBzO3qXpfuzzCvMSDj+NxP920ezsgvHK6cMhoWgYr5+TQcuVrgjCmsI4xE+O8XXpjB8Boce3L+01Zf/ctLYXSIteOa8u5fR3At1KRxDj1fWQmWBBp0z1ygpdlyz2gPaH4epKw=
