language: go
go:
- 1.14.4
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
- sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: Dk9O/mnFU/+RYPRaQLXxENuiwrh1Po1aO2dBttH03nmwWj8eyTHS9fTB6T1gA9x3Xk4DqzelRWEGVHBRL/SyKp3gVTUWAfln5praUV+lZpeu/6WZPiGHx4l1DNZHU3cF8CiWoq7zPVShad2ji97VfkNCEbSixYPdznCYoAeO+mF4zR9gedT/v8zBzwLyCmnEObi5os8/IDPMdgz12trs8BdXIfpvI0Yzkk1lgyb0TCoayCRCTnhqrvDTqSF+dZIzOyWlur+HRiy5ieIFGQIDRDxoar4GKarPbZXIWihBuCdmcYfdtVF6/z0Hb+q5r0L8HQNwX9FNUXA8aEbq/6ElKf5rIzowmb7j1krQUE95jXY7Pg65bBUlLen5XRMAk+O4rVTqO3lw+iA+Fi0WRNg4I1XNExz61cksQYlS2zpo/t9yS3C5hfurJ5JReCwSjdl5elpbLkO9bsHwu0wgqahnDrKLz5yWp6n566nYxDzufQuX1rM/70EbKdV1kFbHJ362n+LMNHrjNEtCONX5EF3Wg26lQXpjnIhNiNBUL6Sf9OokMNcsSn83uGTnaqb4vZ5ete2rmNEKvRftq8X4RFQxkllJ5hX8PcN58d3RbzQf4yylqPI337tc1tqujBL2JK+CU//6tn+yKwYISOP7yWDwR8hCkz8bRkyOzL2oEpvr+44=
  - secure: JocqNN6zhVTfUkB9unbVWHSV1lI4t9BrbRFKQQN9vfCX00qhD6Ts9UuU55bLiqiZS480GdZa9BnebGiAnttK5DUTMe1A+XFcgT58/N57GDZXgg1k0Va0LKU0GI4MEHQroxRpKmQJ1q22TRf4EVDi7Vl6moO9pMH3SqxET2ShYUDKlOjTIv1zmdaM/Tgll8+uaw2WVmfSDQlRuHI4iveown7YA6An38L/umlTNt11HqP4gXlMCgwuh4V4278P+50S+Z/p4pAVAGWidHrsX4NCQ/h6DYeBgoc+L/7OtpxMRk7kPKRSO/+40TU9wl/Wb5JV1Yl/4POrA/+/B1w+p/pvVaT6Za+KQLIen/7hFXxvWmNicyqQFGlEEhRL2wzV59IIiRk7jtglePF/6zc6vw9AN8fMzglK0HT0cLuI9FYXCZD9FRYtUbBjNc4OM+954kdwn+rlmAr9as8cPwtPMJ8WBKvWp2R+zlwtYW6x/BjHsXmLi/tkDK/Aj7xUMXtQAlOjkSFw+VS4XY70AcTFDTimO944sga9k8IBsnS1LHiohKpAwzCcq5v9Ij4nYvtsOnI/5MM2iEIv/+u1mMAY6riPU+CjxsxmHBVUpyiUpD51K1f8pFPPSPVLBQkSYJHDRWe1uPdWUXVWuJU/pyq/cr5kDy6IuGCjf6xtFH/SWQy1USc=
